#!/bin/bash
echo "compiling circuit to r1cs..." &&
date &&
circom circuit.circom --r1cs --wasm --sym &&
npx snarkjs r1cs info circuit.r1cs &&
echo "generating prover and verification keys..." &&
date &&
npx snarkjs zkey new circuit.r1cs ../pot15_final.ptau circuit_init.zkey &&
npx snarkjs zkey contribute circuit_init.zkey circuit.zkey -e="$(date)" &&
npx snarkjs zkey export verificationkey circuit.zkey verification_key.json &&
echo "calculating witness..." &&
date &&
npx snarkjs wtns calculate ./circuit_js/circuit.wasm input.json witness.wtns &&
echo "generating proof..." &&
date &&
npx snarkjs groth16 prove circuit.zkey witness.wtns proof.json public.json
echo "verifying proof..." &&
date &&
npx snarkjs groth16 verify verification_key.json public.json proof.json &&
echo "compiling smart contract..." &&
date &&
npx snarkjs zkey export solidityverifier circuit.zkey verifier.sol &&
echo "clearing files"
rm circuit.r1cs
rm -rf ./circuit_js
rm circuit.sym
rm circuit_init.zkey
rm circuit.zkey
rm verification_key.json
rm verifier.sol
rm proof.json
rm public.json
rm witness.wtns
rm pot15_final.ptau:Zone.Identifier
echo "done!" &&
date